In [ ]:
import datetime as dt
from pathlib import Path
import numpy as np

import pandas as pd

date = dt.date.today()
# date_str = f"{date.year}{date.month}{date.day}"
date_str = "20261014"
a = .25

DATE = Path(date_str)

sym = "A"
opts = pd.read_csv(f"{date_str}/options_snapshot.csv")
unds = pd.read_csv(f"{date_str}/underlyings_snapshot.csv")

In [2]:
filtered_opts = opts[opts["volume"] > 0]
vol_sum_opts = filtered_opts.groupby("underlying")["volume"].sum()
vol_sum_opts = vol_sum_opts.rename("volume_sum")
vol_sum_opts

underlying
A           219.0
AA        17841.0
AADX        283.0
AAL      111266.0
AAOI      32957.0
          ...
_NDX       4002.0
_RUT      61401.0
_SPX    2248514.0
_VIX     999726.0
_XSP      83960.0
Name: volume_sum, Length: 2002, dtype: float64

In [3]:
filtered_opts = filtered_opts.merge(vol_sum_opts, on="underlying", how="left")
filtered_opts["vol_factor"] = filtered_opts["volume"] / filtered_opts["volume_sum"]

In [4]:
filtered_opts

,underlying,contract,expiry,type,strike,bid,ask,volume,open_interest,iv,delta,gamma,theta,vega,rho,volume_sum,vol_factor
0,A,A261016C00170000,2026-10-16,C,170.0,4.70,5.10,4.0,190.0,0.4238,0.7718,0.0517,-0.4519,0.0394,0.0142,219.0,0.018265
1,A,A261016C00175000,2026-10-16,C,175.0,1.65,1.95,35.0,682.0,0.4168,0.4526,0.0689,-0.6470,0.0516,0.0084,219.0,0.159817
2,A,A261120P00150000,2026-11-20,P,150.0,0.85,1.05,3.0,178.0,0.3798,-0.0991,0.0080,-0.0504,0.0977,-0.0181,219.0,0.013699
3,A,A261120P00155000,2026-11-20,P,155.0,1.45,1.75,2.0,137.0,0.3747,-0.1438,0.0109,-0.0632,0.1270,-0.0262,219.0,0.009132
4,A,A261120C00160000,2026-11-20,C,160.0,15.80,18.30,4.0,261.0,0.3486,0.7959,0.0141,-0.0746,0.1578,0.1331,219.0,0.018265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107048,_XSP,XSP281215P00650000,2028-12-15,P,650.0,26.89,28.23,5.0,572.0,0.2298,-0.1721,0.0010,-0.0376,2.8626,-3.4349,83960.0,0.000060
107049,_XSP,XSP281215P00670000,2028-12-15,P,670.0,30.17,31.55,4.0,207.0,0.2239,-0.1920,0.0011,-0.0390,3.0628,-3.8381,83960.0,0.000048
107050,_XSP,XSP281215P00685000,2028-12-15,P,685.0,32.84,34.25,4.0,359.0,0.2195,-0.2080,0.0012,-0.0400,3.2106,-4.1636,83960.0,0.000048
107051,_XSP,XSP281215P00700000,2028-12-15,P,700.0,35.70,37.13,4.0,596.0,0.2152,-0.2250,0.0012,-0.0408,3.3559,-4.5052,83960.0,0.000048
107052,_XSP,XSP281215C01000000,2028-12-15,C,1000.0,21.77,23.29,8.0,253.0,0.1466,0.2586,0.0020,-0.0304,3.6487,3.7944,83960.0,0.000095

In [5]:
unds[["underlying", "price"]]

     underlying      price
0             A   174.1150
1            AA    40.0200
2          AAAU    40.1550
3          AADX    10.4200
4           AAL    11.7800
...         ...        ...
5337       _VIX    16.8700
5338       _XEO  3849.7600
5339       _XND   305.6948
5340       _XSP   771.8900
5341     _XSPBX   772.0200

[5342 rows x 2 columns]

In [6]:
filtered_opts = filtered_opts.merge(unds[["underlying", "price"]], on="underlying", how="left")
filtered_opts = filtered_opts.rename(columns={"price":"underlying_price"})
filtered_opts

,underlying,contract,expiry,type,strike,bid,ask,volume,open_interest,iv,delta,gamma,theta,vega,rho,volume_sum,vol_factor,underlying_price
0,A,A261016C00170000,2026-10-16,C,170.0,4.70,5.10,4.0,190.0,0.4238,0.7718,0.0517,-0.4519,0.0394,0.0142,219.0,0.018265,174.115
1,A,A261016C00175000,2026-10-16,C,175.0,1.65,1.95,35.0,682.0,0.4168,0.4526,0.0689,-0.6470,0.0516,0.0084,219.0,0.159817,174.115
2,A,A261120P00150000,2026-11-20,P,150.0,0.85,1.05,3.0,178.0,0.3798,-0.0991,0.0080,-0.0504,0.0977,-0.0181,219.0,0.013699,174.115
3,A,A261120P00155000,2026-11-20,P,155.0,1.45,1.75,2.0,137.0,0.3747,-0.1438,0.0109,-0.0632,0.1270,-0.0262,219.0,0.009132,174.115
4,A,A261120C00160000,2026-11-20,C,160.0,15.80,18.30,4.0,261.0,0.3486,0.7959,0.0141,-0.0746,0.1578,0.1331,219.0,0.018265,174.115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107048,_XSP,XSP281215P00650000,2028-12-15,P,650.0,26.89,28.23,5.0,572.0,0.2298,-0.1721,0.0010,-0.0376,2.8626,-3.4349,83960.0,0.000060,771.890
107049,_XSP,XSP281215P00670000,2028-12-15,P,670.0,30.17,31.55,4.0,207.0,0.2239,-0.1920,0.0011,-0.0390,3.0628,-3.8381,83960.0,0.000048,771.890
107050,_XSP,XSP281215P00685000,2028-12-15,P,685.0,32.84,34.25,4.0,359.0,0.2195,-0.2080,0.0012,-0.0400,3.2106,-4.1636,83960.0,0.000048,771.890
107051,_XSP,XSP281215P00700000,2028-12-15,P,700.0,35.70,37.13,4.0,596.0,0.2152,-0.2250,0.0012,-0.0408,3.3559,-4.5052,83960.0,0.000048,771.890
107052,_XSP,XSP281215C01000000,2028-12-15,C,1000.0,21.77,23.29,8.0,253.0,0.1466,0.2586,0.0020,-0.0304,3.6487,3.7944,83960.0,0.000095,771.890

In [37]:
filtered_opts["dist"] = abs(filtered_opts["strike"] - filtered_opts["underlying_price"]) / filtered_opts["underlying_price"]
filtered_opts["dist_factor"] = np.where(filtered_opts["dist"] <= a, (filtered_opts["dist"] - a) ** 2 / a ** 2, 0)
filtered_opts

,underlying,contract,expiry,type,strike,bid,ask,volume,open_interest,iv,...,theta,vega,rho,volume_sum,vol_factor,underlying_price,dist_factor,num,den,dist
0,A,A261016C00170000,2026-10-16,C,170.0,4.70,5.10,4.0,190.0,0.4238,...,-0.4519,0.0394,0.0142,219.0,0.018265,174.115,0.819866,1.829408e-04,0.000432,0.023634
1,A,A261016C00175000,2026-10-16,C,175.0,1.65,1.95,35.0,682.0,0.4168,...,-0.6470,0.0516,0.0084,219.0,0.159817,174.115,0.959751,3.385780e-04,0.000812,0.005083
2,A,A261120P00150000,2026-11-20,P,150.0,0.85,1.05,3.0,178.0,0.3798,...,-0.0504,0.0977,-0.0181,219.0,0.013699,174.115,0.198915,7.205816e-04,0.001897,0.138500
3,A,A261120P00155000,2026-11-20,P,155.0,1.45,1.75,2.0,137.0,0.3747,...,-0.0632,0.1270,-0.0262,219.0,0.009132,174.115,0.314569,3.756710e-04,0.001003,0.109784
4,A,A261120C00160000,2026-11-20,C,160.0,15.80,18.30,4.0,261.0,0.3486,...,-0.0746,0.1578,0.1331,219.0,0.018265,174.115,0.456613,5.161643e-04,0.001481,0.081067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107048,_XSP,XSP281215P00650000,2028-12-15,P,650.0,26.89,28.23,5.0,572.0,0.2298,...,-0.0376,2.8626,-3.4349,83960.0,0.000060,771.890,0.135686,2.161027e-06,0.000009,0.157911
107049,_XSP,XSP281215P00670000,2028-12-15,P,670.0,30.17,31.55,4.0,207.0,0.2239,...,-0.0390,3.0628,-3.8381,83960.0,0.000048,771.890,0.222781,1.408049e-06,0.000006,0.132001
107050,_XSP,XSP281215P00685000,2028-12-15,P,685.0,32.84,34.25,4.0,359.0,0.2195,...,-0.0400,3.2106,-4.1636,83960.0,0.000048,771.890,0.302202,1.177163e-06,0.000005,0.112568
107051,_XSP,XSP281215P00700000,2028-12-15,P,700.0,35.70,37.13,4.0,596.0,0.2152,...,-0.0408,3.3559,-4.5052,83960.0,0.000048,771.890,0.393706,9.548670e-07,0.000004,0.093135
107052,_XSP,XSP281215C01000000,2028-12-15,C,1000.0,21.77,23.29,8.0,253.0,0.1466,...,-0.0304,3.6487,3.7944,83960.0,0.000095,771.890,0.000000,4.128007e-06,0.000028,0.295521

In [40]:
filtered_opts.loc[filtered_opts["dist_factor"] == 0]

,underlying,contract,expiry,type,strike,bid,ask,volume,open_interest,iv,...,theta,vega,rho,volume_sum,vol_factor,underlying_price,dist_factor,num,den,dist
13,A,A270319C00240000,2027-03-19,C,240.0,1.70,1.95,31.0,101.0,0.3422,...,-0.0231,0.2184,0.0744,219.0,0.141553,174.115,0.0,0.018329,0.053563,0.378399
57,AA,AA261218C00055000,2026-12-18,C,55.0,0.25,0.28,11.0,1917.0,0.4843,...,-0.0091,0.0252,0.0053,17841.0,0.000617,40.020,0.0,0.000112,0.000231,0.374313
58,AA,AA261218P00060000,2026-12-18,P,60.0,19.85,20.65,15.0,348.0,0.6698,...,-0.0067,0.0067,-0.0098,17841.0,0.000841,40.020,0.0,0.000281,0.000420,0.499250
70,AA,AA270115P00055000,2027-01-15,P,55.0,14.20,15.75,3.0,2021.0,0.3796,...,-0.0052,0.0312,-0.0519,17841.0,0.000168,40.020,0.0,0.000024,0.000063,0.374313
71,AA,AA270115C00065000,2027-01-15,C,65.0,0.13,0.15,61.0,4308.0,0.4946,...,-0.0044,0.0176,0.0038,17841.0,0.003419,40.020,0.0,0.001056,0.002134,0.624188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106992,_XSP,XSP270219P00480000,2027-02-19,P,480.0,1.11,1.18,3.0,118.0,0.4076,...,-0.0283,0.1901,-0.0479,83960.0,0.000036,771.890,0.0,0.000006,0.000014,0.378150
106993,_XSP,XSP270219P00560000,2027-02-19,P,560.0,2.12,2.18,1.0,151.0,0.3273,...,-0.0434,0.3609,-0.1023,83960.0,0.000012,771.890,0.0,0.000001,0.000003,0.274508
107032,_XSP,XSP270617P00400000,2027-06-17,P,400.0,1.54,1.68,11.0,179.0,0.4190,...,-0.0200,0.2515,-0.0901,83960.0,0.000131,771.890,0.0,0.000026,0.000063,0.481791
107038,_XSP,XSP270820P00510000,2027-08-20,P,510.0,4.61,4.74,1.0,121.0,0.3157,...,-0.0337,0.7013,-0.3393,83960.0,0.000012,771.890,0.0,0.000001,0.000004,0.339284
107052,_XSP,XSP281215C01000000,2028-12-15,C,1000.0,21.77,23.29,8.0,253.0,0.1466,...,-0.0304,3.6487,3.7944,83960.0,0.000095,771.890,0.0,0.000004,0.000028,0.295521

In [17]:
filtered_opts = filtered_opts.drop("comp_iv", axis=1)

In [42]:
# syms = unds["underlying"]
num = filtered_opts["vol_factor"] * filtered_opts["dist_factor"] * filtered_opts["iv"]
den = filtered_opts["vol_factor"] * filtered_opts["dist_factor"]
filtered_opts["num"] = num
filtered_opts["den"] = den
summed = filtered_opts.groupby("underlying", as_index=False)[["num", "den"]].sum()
summed["comp_iv"] = summed["num"] / summed["den"]
summed

     underlying       num       den   comp_iv
0             A  0.246139  0.681634  0.361102
1            AA  0.332052  0.438079  0.757973
2          AADX  0.229133  0.334656  0.684681
3           AAL  0.199623  0.416109  0.479739
4          AAOI  0.328993  0.312123  1.054047
...         ...       ...       ...       ...
1997       _NDX  0.153310  0.718610  0.213342
1998       _RUT  0.150927  0.725571  0.208011
1999       _SPX  0.772074  0.800236  0.964808
2000       _VIX  0.233613  0.319787  0.730528
2001       _XSP  0.123662  0.864014  0.143125

[2002 rows x 4 columns]

In [43]:
final_opts = filtered_opts.merge(summed[["underlying", "comp_iv"]], on="underlying", how="left")
final_opts

,underlying,contract,expiry,type,strike,bid,ask,volume,open_interest,iv,...,vega,rho,volume_sum,vol_factor,underlying_price,dist_factor,num,den,dist,comp_iv
0,A,A261016C00170000,2026-10-16,C,170.0,4.70,5.10,4.0,190.0,0.4238,...,0.0394,0.0142,219.0,0.018265,174.115,0.819866,0.006346,0.014975,0.023634,0.361102
1,A,A261016C00175000,2026-10-16,C,175.0,1.65,1.95,35.0,682.0,0.4168,...,0.0516,0.0084,219.0,0.159817,174.115,0.959751,0.063931,0.153385,0.005083,0.361102
2,A,A261120P00150000,2026-11-20,P,150.0,0.85,1.05,3.0,178.0,0.3798,...,0.0977,-0.0181,219.0,0.013699,174.115,0.198915,0.001035,0.002725,0.138500,0.361102
3,A,A261120P00155000,2026-11-20,P,155.0,1.45,1.75,2.0,137.0,0.3747,...,0.1270,-0.0262,219.0,0.009132,174.115,0.314569,0.001076,0.002873,0.109784,0.361102
4,A,A261120C00160000,2026-11-20,C,160.0,15.80,18.30,4.0,261.0,0.3486,...,0.1578,0.1331,219.0,0.018265,174.115,0.456613,0.002907,0.008340,0.081067,0.361102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107048,_XSP,XSP281215P00650000,2028-12-15,P,650.0,26.89,28.23,5.0,572.0,0.2298,...,2.8626,-3.4349,83960.0,0.000060,771.890,0.135686,0.000002,0.000008,0.157911,0.143125
107049,_XSP,XSP281215P00670000,2028-12-15,P,670.0,30.17,31.55,4.0,207.0,0.2239,...,3.0628,-3.8381,83960.0,0.000048,771.890,0.222781,0.000002,0.000011,0.132001,0.143125
107050,_XSP,XSP281215P00685000,2028-12-15,P,685.0,32.84,34.25,4.0,359.0,0.2195,...,3.2106,-4.1636,83960.0,0.000048,771.890,0.302202,0.000003,0.000014,0.112568,0.143125
107051,_XSP,XSP281215P00700000,2028-12-15,P,700.0,35.70,37.13,4.0,596.0,0.2152,...,3.3559,-4.5052,83960.0,0.000048,771.890,0.393706,0.000004,0.000019,0.093135,0.143125
107052,_XSP,XSP281215C01000000,2028-12-15,C,1000.0,21.77,23.29,8.0,253.0,0.1466,...,3.6487,3.7944,83960.0,0.000095,771.890,0.000000,0.000000,0.000000,0.295521,0.143125

In [47]:
unds_ivs = unds[["underlying", "iv30"]]
unds_ivs = unds_ivs.merge(summed[["underlying", "comp_iv"]], on="underlying", how="left")
unds_ivs

     underlying    iv30   comp_iv
0             A  35.150  0.361102
1            AA  49.915  0.757973
2          AAAU  21.582       NaN
3          AADX  72.267  0.684681
4           AAL  46.761  0.479739
...         ...     ...       ...
5337       _VIX  84.472  0.730528
5338       _XEO  13.033       NaN
5339       _XND  18.422       NaN
5340       _XSP  13.141  0.143125
5341     _XSPBX   7.310       NaN

[5342 rows x 3 columns]

In [48]:
unds_ivs["dif"] = unds_ivs["iv30"] / 100 - unds_ivs["comp_iv"]
unds_ivs

     underlying    iv30   comp_iv       dif
0             A  35.150  0.361102 -0.009602
1            AA  49.915  0.757973 -0.258823
2          AAAU  21.582       NaN       NaN
3          AADX  72.267  0.684681  0.037989
4           AAL  46.761  0.479739 -0.012129
...         ...     ...       ...       ...
5337       _VIX  84.472  0.730528  0.114192
5338       _XEO  13.033       NaN       NaN
5339       _XND  18.422       NaN       NaN
5340       _XSP  13.141  0.143125 -0.011715
5341     _XSPBX   7.310       NaN       NaN

[5342 rows x 4 columns]

In [49]:
min_dif, max_dif = min(unds_ivs["dif"]), max(unds_ivs["dif"])
print("min dif b/t composite iv and listed iv is...", min_dif)
print("max dif b/t composite iv and lsited iv is...", max_dif)

min dif b/t composite iv and listed iv is... -3.3478100000000004
max dif b/t composite iv and lsited iv is... 0.5863600000000001